---

- hosts: all

  vars:
      ###
      # Main Directories
      ###
      client: /vagrant/client
      server: /vagrant/server

      ###
      # Node Directories
      ###
      node_modules_mountpoint: /vagrant/client/node_modules
      node_modules_directory: /srv/client/node_modules

  tasks:

  - name: Install a few packages
    yum: name={{item}}
    with_items: 
      - nodejs
      - git
      - httpd
      - httpd-devel
      - python-devel
      - python-pip
      - python34-devel.x86_64
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
      - postgresql-devel
      - gcc
      - mod_wsgi
    sudo: yes

  
  - name: Initiate database
    sudo: yes
    command: service postgresql initdb
            creates=/var/lib/pgsql/data/postgresql.conf

  - name: Start PostgreSQL and enable at boot
    sudo: yes
    service: name=postgresql
            enabled=yes
            state=started

  - lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
               regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
               line='host all all 127.0.0.1/32 md5'
               insertbefore=BOF
    notify: restart postgresql
    sudo: yes

  - name: Create PostgreSQL User
    shell: psql -c "ALTER USER postgres PASSWORD 'password';"
    sudo: yes
    sudo_user: postgres

  - name: Create PostgreSQL Database
    shell: createdb mydb
    failed_when: False
    sudo: yes
    sudo_user: postgres
    
  - name: Pip Install
    pip: requirements={{server}}/requirements.txt executable=pip3.4
    sudo: yes

  - name: Copy Apache config
    copy: src=django.conf dest=/etc/httpd/conf.d/django.conf
    sudo: yes
    notify: restart httpd

  - name: Mount node modules mount point to fstab
    mount:  src={{ node_modules_directory }}
            name={{ node_modules_mountpoint }}
            opts="bind"
            fstype=none
            state=mounted
    sudo: yes

  - name: Install Node modules
    command: sudo npm install chdir={{client}}

  handlers:

  - name: restart postgresql
    sudo: yes
    service: name=postgresql state=restarted

  - name: restart httpd
    sudo: yes
    service: name=httpd state=restarted